displayName: Traefik Signature Verifier
type: middleware
import: github.com/othmane222/testplugin
summary: Verifies request signatures based on Authorization, X-Date, and a shared secret key.
testData:
  secretKey: "Oj2eKc2nZwzTIRYBWEmOT4rKggn53meG"


